using NUnit.Framework;
using OpenQA.Selenium;
using OpenQA.Selenium.Support.UI;
using SeleniumExtras.PageObjects;
using SeleniumExtras.WaitHelpers;
using System;
using System.Linq;
using System.Threading;
using TechTalk.SpecFlow;

namespace SeeSharpWebAutomation.PageObject
{
    class ContactUs
    {
        public static Random random = new Random();
        public static string RandomString(int length)
        {
            const string chars = "abcdefghijklmnopqrstuvwxyz";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }
        public static string RandomOrder(int length)
        {
            const string chars = "12357890";
            return new string(Enumerable.Repeat(chars, length)
              .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        private string email = RandomString(5) + "@mail.org";
        private string order = RandomOrder(8);
        private string message = "This message was generated by a automated test";

        private WebDriverWait wait;
        public ContactUs()
        {
            wait = ScenarioContext.Current.Get<WebDriverWait>("Wait");
        }

        [FindsBy(How = How.XPath, Using = "//div[@id='center_column']/h1")]
        public IWebElement CustomerServiceHeader { get; set; }
        [FindsBy(How = How.XPath, Using = "//select[@id='id_contact']")]
        public IWebElement SubjectHeading { get; set; }
        [FindsBy(How = How.XPath, Using = "//select[@id='id_contact']/option[2]")]
        public IWebElement SubjectHeadingOption { get; set; }
        [FindsBy(How = How.XPath, Using = "//input[@id='email']")]
        public IWebElement EmailInput { get; set; }
        [FindsBy(How = How.XPath, Using = "//input[@id='id_order']")]
        public IWebElement OrderInput { get; set; }
        [FindsBy(How = How.XPath, Using = "//textarea[@id='message']")]
        public IWebElement MessageTextArea { get; set; }
        [FindsBy(How = How.XPath, Using = "//button[@id='submitMessage']")]
        public IWebElement SubmitButton { get; set; }
        [FindsBy(How = How.XPath, Using = "//p[@class='alert alert-success']")]
        public IWebElement SuccessAlert { get; set; }

        public void ContactUsForm(IWebDriver driver)
        {
            PageFactory.InitElements(driver, this);
            Assert.That(CustomerServiceHeader.Displayed);
        }
        public void FillingForm(IWebDriver driver)
        {
            PageFactory.InitElements(driver, this);
            SubjectHeading.Click();
            wait.Until(ExpectedConditions.ElementToBeClickable(SubjectHeadingOption));
            SubjectHeadingOption.Click();
            EmailInput.SendKeys(email);
            OrderInput.SendKeys(order);
            MessageTextArea.SendKeys(message);
        }
        public void SendMessage(IWebDriver driver)
        {
            PageFactory.InitElements(driver, this);
            SubmitButton.Click();
            wait.Until(ExpectedConditions.ElementExists(By.XPath("//p[@class='alert alert-success']")));
            Assert.That(SuccessAlert.Displayed);
        }
    }
}
